services:

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:newpassword123@db:5432/taskmanager
    depends_on:
       db:
        condition: service_healthy
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=newpassword123
      - POSTGRES_DB=taskmanager
    volumes:
       - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d taskmanager"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:


